[
build
]
  command = "npm run build"
  publish = "dist"  # Change this to "build" if using Create React App

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200

[[
headers
]]
  for = "/*.js"
  [
headers.values
]
    Content-Type = "text/javascript"

[[
headers
]]
  for = "/*.css"
  [
headers.values
]
    Content-Type = "text/css"